# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Nodejs sync orders tiktok k

on:
  schedule:
    - cron: "*/20 * * * *"
  workflow_dispatch:
    inputs:
      TABLE_ORDERS_NAME:
        description: "Tên bảng Orders"
        required: true
        type: string

      TABLE_ORDER_ITEMS_NAME:
        description: "Tên bảng Order Items"
        required: true
        type: string

      FROM:
        description: "Từ ngày (YYYY/MM/DD)"
        required: true
        type: string

      TO:
        description: "Đến ngày (YYYY/MM/DD)"
        required: true
        type: string

jobs:
  sync-orders-job:
    runs-on: ubuntu-latest
    environment: sync-order

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci --only=production

      - name: Run sync-orders-k.js
        env:
          AES_256_CBC_APP_SECRET_KEY: ${{ secrets.AES_256_CBC_APP_SECRET_KEY }}
          DATABASE_SERVICE_KEY: ${{ secrets.DATABASE_SERVICE_KEY }}
          KIOTVIET_RETAILER: ${{ secrets.KIOTVIET_RETAILER }}
          KIOTVIET_RETAILER_OLD: ${{ secrets.KIOTVIET_RETAILER_OLD}}
          KIOT_CLIENT_ID: ${{ secrets.KIOT_CLIENT_ID }}
          KIOT_CLIENT_ID_OLD: ${{ secrets.KIOT_CLIENT_ID_OLD }}
          KIOT_SECRET: ${{ secrets.KIOT_SECRET }}
          KIOT_SECRET_OLD: ${{ secrets.KIOT_SECRET_OLD}}
          LARK_TIKTOK_K_ORDER_ITEMS_APP_ID: ${{ secrets.LARK_TIKTOK_K_ORDER_ITEMS_APP_ID }}
          LARK_TIKTOK_K_ORDER_ITEMS_APP_SECRET: ${{ secrets.LARK_TIKTOK_K_ORDER_ITEMS_APP_SECRET }}
          TIKTOK_PARTNER_APP_KEY_7561567100864644872: ${{ secrets.TIKTOK_PARTNER_APP_KEY_7561567100864644872 }}
          TIKTOK_PARTNER_APP_SECRET_7561567100864644872: ${{ secrets.TIKTOK_PARTNER_APP_SECRET_7561567100864644872 }}
          BASE_ID_TMDT: ${{ vars.BASE_ID_TMDT }}
          TABLE_ORDERS_NAME: ${{ inputs.TABLE_ORDERS_NAME || vars.TABLE_ORDERS_NAME }}
          TABLE_ORDER_ITEMS_NAME: ${{ inputs.TABLE_ORDER_ITEMS_NAME || vars.TABLE_ORDER_ITEMS_NAME }}
          TABLE_SKUS: ${{ vars.TABLE_SKUS }}
          FROM: ${{ inputs.FROM || vars.FROM }}
          TO: ${{ inputs.TO || vars.TO }}

        run: node sync-orders-k.js
